sources:
  - name: airbnb_shantanu
    schema: raw
    tables:
    - name: listings
      identifier: raw_listings

    - name: reviews
      identifier: raw_reviews
      config:
        loaded_at_field: date
        freshness:
          warn_after: {count: 1, period: hour}
          # error_after: {count: 24, period: hour}

    - name: hosts
      identifier: RAW_HOSTS